npm install gulp
npm install del
npm install gulp
npm install gulp-concat
npm install gulp-minify-css
npm install gulp-uglify
npm install gulp-sourcemaps
npm install gulp-rename
npm install gulp-bower
npm install gulp-connect
npm install gulp-watch
npm install bower
